version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-northeast-1:497217256558:task-definition/onboarding-kw-td:2"
        LoadBalancerInfo:
          ContainerName: "onboarding-nginx-kw"
          ContainerPort: 80